global:
  scrape_interval: 15s # 시스템 부하를 고려한 권장 수집 주기

scrape_configs:
  - job_name: 'flight-monitor-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['flight-main-app:8080'] # 단일 노드만 타겟팅